### ISSUE TITLE
Issue with start app

### ISSUE THREAD

**Issue by yurgon** [stephenmoloney/openstex_adapters_ovh#3]
Hi, sometimes I get error like:

```** (Mix) Could not start application arc_ovh: ArcOvh.Application.start(:normal, []) returned an error: shutdown: failed to start child: ArcOvh.Client.Cloudstorage
    ** (EXIT) shutdown: failed to start child: Openstex.Adapters.Ovh.Config
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, %HTTPipe.Conn{adapter: HTTPipe.Adapters.Hackney, adapter_options: [timeout: 10000, recv_timeout: 30000], error: %HTTPipe.Adapters.Hackney.RequestError{message: "Hackney encountered an error while attempting to communicate with\nthe server. The reason given was:\n\nclosed\n"}, options: %{defer_body_processing: false}, request: %HTTPipe.Request{body: nil, headers: %{"Content-Type" => "application/json; charset=utf-8", "X-Auth-Token" => "CODE"}, http_version: "1.1", method: :get, params: %{}, url: "https://storage.gra1.cloud.ovh.net/v1/AUTH_CODE"}, response: nil, status: :failed}}
                (openstex_adapters_ovh) lib/openstex/ovh/config/config.ex:156: Openstex.Adapters.Ovh.Config.get_account_temp_url/3
                (openstex_adapters_ovh) lib/openstex/ovh/config/config.ex:92: Openstex.Adapters.Ovh.Config.swift_config/3
                (openstex_adapters_ovh) lib/openstex/ovh/config/config.ex:44: Openstex.Adapters.Ovh.Config.config/3
                (elixir) lib/agent/server.ex:8: Agent.Server.init/1
                (stdlib) gen_server.erl:365: :gen_server.init_it/2
                (stdlib) gen_server.erl:333: :gen_server.init_it/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I think better - dont get every time new token from OVH. Need to create token with unlimited and added to config.

**Comment by stephenmoloney** [comment]
yes - this is definitely something i am going to do - just not sure when just yet

**Comment by yurgon** [comment]
Hello
Any news

**Comment by stephenmoloney** [comment]
hopefully soon... I'll let you know!
